# Generated by Django 5.2 on 2025-04-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('message', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=12)),
                ('status', models.BooleanField()),
                ('send_date', models.DateField()),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.header')),
            ],
        ),
    ]
