# Generated by Django 5.2 on 2025-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='times',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
